# Disable the blank line at the start of the prompt
add_newline = false

[hostname]
ssh_only = false
format =  "@[$hostname](bold blue) "
trim_at = "."
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user](bold green)"
disabled = false
show_always = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[](bold purple) "
error_symbol = "[✖](bold red) "

[directory]
read_only = " "
